"""Create prices table

Revision ID: 4b0dbb320af6
Revises: 109ac1f5eabc
Create Date: 2026-01-14 18:56:45.005753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b0dbb320af6'
down_revision: Union[str, None] = '109ac1f5eabc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('mark_iv', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_instrument_timestamp', 'prices', ['instrument_name', 'timestamp'], unique=False)
    op.create_index('idx_timestamp', 'prices', ['timestamp'], unique=False)
    op.create_index(op.f('ix_prices_id'), 'prices', ['id'], unique=False)
    op.create_index(op.f('ix_prices_instrument_name'), 'prices', ['instrument_name'], unique=False)
    op.drop_index('ix_price_ticks_id', table_name='price_ticks')
    op.drop_index('ix_price_ticks_ticker', table_name='price_ticks')
    op.drop_index('ix_price_ticks_timestamp', table_name='price_ticks')
    op.drop_table('price_ticks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_ticks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='price_ticks_pkey')
    )
    op.create_index('ix_price_ticks_timestamp', 'price_ticks', ['timestamp'], unique=False)
    op.create_index('ix_price_ticks_ticker', 'price_ticks', ['ticker'], unique=False)
    op.create_index('ix_price_ticks_id', 'price_ticks', ['id'], unique=False)
    op.drop_index(op.f('ix_prices_instrument_name'), table_name='prices')
    op.drop_index(op.f('ix_prices_id'), table_name='prices')
    op.drop_index('idx_timestamp', table_name='prices')
    op.drop_index('idx_instrument_timestamp', table_name='prices')
    op.drop_table('prices')
    # ### end Alembic commands ###
